version: '3'
services:
  matching-engine:
    image: proofsuite/amp-matching-engine:latest
    ports:
      - "8081:8081"
    environment:
      - AMP_ETHEREUM_NODE_URL=ws://ethereum:8546
      - AMP_MONGO_URL=mongodb
      - AMP_MONGO_DBNAME
      - AMP_REDIS_URL=redis://redis:6379
      - AMP_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - AMP_EXCHANGE_CONTRACT_ADDRESS
      - AMP_WETH_CONTRACT_ADDRESS
      - AMP_FEE_ACCOUNT_ADDRESS
    depends_on:
      - mongodb
      - rabbitmq
      - redis
      - ethereum
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  client:
    image: proofsuite/amp-client:latest
    container_name: "client"
    ports:
      - "8080:8080"
    environment:
      - AMP_ENGINE_HTTP_URL=http://localhost:8081
      - AMP_ENGINE_WS_URL=ws://localhost:8081
      - AMP_ETHEREUM_NODE_HTTP_URL=http://localhost:8545
      - AMP_ETHEREUM_NODE_WS_URL=ws://localhost:8546
      - AMP_ETHEREUM_NETWORK_ID=8888
    depends_on:
      - matching-engine
      - ethereum
    command: >
       bin/bash -c "chmod +x ./replace.sh && ./replace.sh && cat build/env.js && yarn server"


  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ${AMP_MONGO_DBPATH}:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq
    container_name: "rabbitmq"
    ports:
      - '5672:5672'

  redis:
    image: redis
    container_name: "redis"
    ports:
      - '6379:6379'

  ethereum:
    image: ethereum/client-go
    container_name: "ethereum"
    ports:
      - "8546:8546"
      - "8545:8545"
    volumes:
      - ./${AMP_ETHEREUM_DATADIR}:/root/.ethereum
      - ./${AMP_ETHEREUM_DAG}:/root/.ethash
      - ./${AMP_ETHEREUM_GENESIS}:/root/genesis.json
      - ./${AMP_ETHEREUM_DAG_CACHE}:/root/.ethereum/geth/ethash
    command: [
      "--port", "3001",
      "--networkid", $AMP_ETHEREUM_NETWORK_ID,
      "--nodiscover",
      "--maxpeers", "0",
      "--ws", "--wsport", "8546", "--wsaddr", "0.0.0.0",
      "--rpc", "--rpcport", "8545", "--rpcaddr", "127.0.0.1",
      "--wsorigins", "*",
      "--wsapi", "eth,net,web3,personal",
      "--minerthreads", "1",
      "--mine",
      "--etherbase", $AMP_ETHERBASE,
      "--rpccorsdomain", "*",
      "--ipcpath", "/root/.ethereum/"
    ]