# This docker compose file starts processes on remote aws instances
# For this, docker needs to be in swarm mode with the following nodes
# - engine
# - rabbitmq
# - client
# - redis
# - mongodb
# - ethereum
#  To work properly the ethereum node and other services might have
# to be removed and simply working with external services

version: '3'
services:
  ethereum:
    image: ethereum/client-go
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "ethereum_root:/root/.ethereum"
    environment:
      - AMP_RINKEBY_ETHERBASE
    command: [
      "--port", "30303",
      "--syncmode", "fast",
      "--cache", "1024",
      "--rinkeby",
      "--datadir", "/root/.ethereum",
      "--wsapi", "admin,eth,net,web3,personal",
      "--rpcapi", "admin,eth,net,web3,personal",
      "--rpc", "--rpcport", "8545", "--rpcaddr", "0.0.0.0",
      "--ws", "--wsport", "8546", "--wsaddr", "0.0.0.0",
      "--wsorigins", "*",
      "--etherbase", $AMP_RINKEBY_ETHERBASE,
      "--rpccorsdomain", "*",
    ]
    networks:
      amp:
        aliases:
        - ethereum
    deploy:
      placement:
        constraints:
          - node.hostname == ethereum
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      amp:
        aliases:
        - redis
    volumes:
      - "redis_data:/data"
    entrypoint: redis-server --appendonly yes
    deploy:
      placement:
        constraints:
          - node.hostname == redis
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      amp:
        aliases:
        - rabbitmq
    volumes:
      - "rabbitmq_logs:/var/log/rabbitmq"
      - "rabbitmq_data:/var/lib/rabbitmq"
    deploy:
      placement:
        constraints:
          - node.hostname == rabbitmq
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      amp:
        aliases:
        - mongodb
    volumes:
    - "mongodb_data:/data/db"
    deploy:
      placement:
        constraints:
          - node.hostname == mongodb
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  client:
    image: proofsuite/amp-client:staging
    ports:
      - "80:80"
    environment:
      - AMP_ENGINE_HTTP_URL=/engine
      - AMP_ETHEREUM_NODE_HTTP_URL=/ethereum
      - AMP_ENGINE_WS_URL=ws://${AMP_RINKEBY_MATCHING_ENGINE_IP:-13.125.100.61}:8081
      - AMP_ETHEREUM_NODE_WS_URL=ws://${AMP_RINKEBY_ETHEREUM_IP:-13.125.62.193}:8545
      - AMP_ETHEREUM_NETWORK_ID=4
    depends_on:
      - matching-engine
      - ethereum
    networks:
      amp:
        aliases:
        - client
    deploy:
      placement:
        constraints:
          - node.hostname == client
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    command: >
         bin/sh -c "sleep 10 && chmod +x ./replace.sh && sleep 1 && ./replace.sh && cat /usr/share/nginx/html/env.js && nginx -g 'daemon off;'"


  matching-engine:
    image: proofsuite/amp-matching-engine:staging
    ports:
      - '8081:8081'
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    environment:
      - AMP_ETHEREUM_NODE_HTTP_URL=http://ethereum:8545
      - AMP_ETHEREUM_NODE_WS_URL=ws://ethereum:8546
      - AMP_MONGODB_URL=mongodb
      - AMP_MONGODB_DBNAME=proofdex
      - AMP_REDIS_URL=redis://redis:6379
      - AMP_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - AMP_EXCHANGE_CONTRACT_ADDRESS=${AMP_RINKEBY_EXCHANGE_CONTRACT_ADDRESS}
      - AMP_WETH_CONTRACT_ADDRESS=${AMP_RINKEBY_WETH_CONTRACT_ADDRESS}
      - AMP_FEE_ACCOUNT_ADDRESS=${AMP_RINKEBY_FEE_ACCOUNT_ADDRESS}
    networks:
      amp:
        aliases:
        - matching-engine
    deploy:
      placement:
        constraints:
          - node.hostname == matching-engine
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s


networks:
  amp:
    external: true

volumes:
  ethereum_root:
  rabbitmq_logs:
  rabbitmq_data:
  redis_data:
  mongodb_data:
